apiVersion: apps/v1
kind: Deployment
metadata:
  name: enc-server-py-be
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enc-server-py-be
  template:
    metadata:
      labels:
        app: enc-server-py-be
    spec:
      containers:
      - name: enc-server-py-be
        image: enc-server-py-enc-server-py-be:latest
        imagePullPolicy: Never
        env:
        - name: ENC_SERVER_PY_CONFIG_PATH
          value: "config/config.kube.yaml"
        command:
          - make
          - beserver
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: enc-server-py-be
  namespace: default
spec:
  type: NodePort
  selector:
    app: enc-server-py-be
  ports:
  - port: 8888
    targetPort: 8888
