apiVersion: apps/v1
kind: Deployment
metadata:
  name: enc-server-py-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enc-server-py-db
  template:
    metadata:
      labels:
        app: enc-server-py-db
    spec:
      containers:
      - name: mongodb
        image: mongodb/mongodb-community-server:6.0-ubi8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: enc-server-py-db
  namespace: default
spec:
  type: NodePort
  selector:
    app: enc-server-py-db
  ports:
  - port: 27017
    targetPort: 27017
