{
    "feClientConfigs": {
        "serverAddr": "localhost:7777"
    },
    
    "feServerConfigs": {
        "keySize": "32",
        "idKeyStr": "vkAZAarLbZ6w0kmL2HJP3eU1ODCgVj4k",
        "idNonceStr": "9bc423909ac5",
        "port": "7777"
    },
    
    "beServerConfigs": {
        "port": "8888",
        "mongoURI": "mongodb://localhost:27017"
    },
    
    "beClientConfigs": {
        "serverAddr": "localhost:8888"
    },
    
    "testParams": {
        "id": "JTH",
        "record": "PAYLOADSPAYLOADSPAYLOADSPAYLOADSPAYLOADSPAYLOADSPAYLOADSPAYLOADS"
    }
}
