name: Py

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Py
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: '7.0.2'

    - name: Install
      run: make install
        
    - name: Unit Tests
      run: make tests

    - name: Start Servers 
      run: make servers

    - name: Integration Test s
      run: make itests

    - name: Stop Servers
      run: make stop
